/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: false
    inverse1: false
    inverse2: false
    laser1Alpha: 0.0
    laser1AngleMax: 130.0
    laser1AngleMin: -130.0
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: 0.0
    laser1YOff: 0.0
    laser1ZOff: 0.0
    laser2Alpha: 180.0
    laser2AngleMax: 130.0
    laser2AngleMin: -130.0
    laser2B: 255
    laser2G: 0
    laser2R: 0
    laser2XOff: -0.854
    laser2YOff: -0.144
    laser2ZOff: 0.0
    pointCloudTopic: cloud_in
    pointCloutFrameId: front_laser_base_link
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /summit/front_laser/scan
    scanTopic2: /summit/rear_laser/scan
    show1: true
    show2: true
    use_sim_time: false

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.004363323096185923
    # angle_max: 1.5708
    # angle_min: -1.5708
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 1.0
    min_height: -1.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 61.0
    range_min: 0.023000000044703484
    scan_time: 0.02500000037252903
    target_frame: front_laser_base_link
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false
